---

- hosts: all
  become: true
  tasks:

  - name: update repository index, install apache and php packages for Ubuntu
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes